apiVersion: v1
kind: ConfigMap
metadata:
  name: supportgpt-config
  namespace: default
data:
  APP_ENV: "production"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres-svc:5432/supportgpt"
  REDIS_URL: "redis://redis-svc:6379/0"
  LLM_PROVIDER: "mock"
  VECTOR_DB_PERSIST_DIR: "/data/chromadb"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector:4318/v1/metrics"
  OTEL_METRIC_EXPORT_INTERVAL_MILLISECONDS: "15000"
